# -*- coding: utf-8 -*-
"""Model_Building

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNF3PP-soe4UlkNX2Oqibib3mdckpUtd
"""

# ============================================================
# HDB RESALE PRICE
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LassoCV, RidgeCV
from sklearn.ensemble import RandomForestRegressor
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# SECTION 1: LOAD DATA
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/hdb_with_school_features.csv')
print(f"Raw shape: {df.shape}")

# ============================================================
# SECTION 2: PREPROCESSING
# ============================================================

# 2.1 Drop irrelevant/identifier columns
# good_sch_lt_2km is dropped because it equals good_sch_lt_1km + good_sch_1_2km
# perfect linear combination of the other two school variables → causes multicollinearity
drop_cols = [
    'Unnamed: 0', 'address', 'block', 'road_code', 'street_name',
    'block_key', 'st_cod_key', 'geom_wkt', 'sold_year_month',
    'sold_remaining_lease',  # redundant with remaining_lease_2026
    'good_sch_lt_2km'        # redundant: = good_sch_lt_1km + good_sch_1_2km
]
df = df.drop(columns=drop_cols)

# 2.2 Exclude 2026 (incomplete year, only 4,768 rows)
df = df[df['sold_year'] <= 2025].copy()
print(f"Shape after dropping 2026: {df.shape}")

# 2.3 Extract storey midpoint from storey_range string
# e.g. "04 TO 06" → 5.0
def extract_storey_midpoint(s):
    parts = s.strip().split(' TO ')
    return (int(parts[0]) + int(parts[1])) / 2

df['storey_mid'] = df['storey_range'].apply(extract_storey_midpoint)
df = df.drop(columns=['storey_range'])

# 2.4 Encode binary amenity columns (Y/N → 1/0)
binary_cols = ['market_hawker', 'miscellaneous', 'multistorey_carpark', 'precinct_pavilion']
for col in binary_cols:
    df[col] = (df[col].str.strip().str.upper() == 'Y').astype(int)

# 2.5 One-hot encode categorical columns
# drop_first=True avoids dummy variable trap (perfect multicollinearity)
cat_cols = ['town', 'flat_type', 'flat_model']
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

# Convert boolean dummy columns to int (required for statsmodels)
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

print(f"Final preprocessed shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

# ============================================================
# SECTION 3: TRAIN / TEST SPLIT (TEMPORAL)
# ============================================================
# Temporal split is used instead of random split because:
# - Simulates real-world forecasting (train on past, predict future)
# - Random split would leak future information into training

train = df[df['sold_year'] <= 2023].copy()
test  = df[df['sold_year'].isin([2024, 2025])].copy()

SCHOOL_COLS = ['good_sch_lt_1km', 'good_sch_1_2km', 'good_sch_gt_2km']
TARGET = 'resale_price'
feature_cols = [c for c in df.columns if c != TARGET]

X_train, y_train = train[feature_cols], train[TARGET]
X_test,  y_test  = test[feature_cols],  test[TARGET]

print(f"\nTrain: {X_train.shape} | Test: {X_test.shape}")
print(f"Train years: {train['sold_year'].min()}–{train['sold_year'].max()}")
print(f"Test years:  {test['sold_year'].min()}–{test['sold_year'].max()}")

# ============================================================
# SECTION 4: BASELINE MODEL
# ============================================================
# Predicts the training mean for every observation.

y_pred_baseline = np.full(len(y_test), y_train.mean())
baseline_rmse = np.sqrt(mean_squared_error(y_test, y_pred_baseline))
baseline_r2   = r2_score(y_test, y_pred_baseline)

print(f"\n[Baseline] RMSE: ${baseline_rmse:,.0f} | R²: {baseline_r2:.4f}")

# ============================================================
# SECTION 5A: OLS — INITIAL RUN (before multicollinearity fix)
# ============================================================
# Shows high VIF for good_sch_gt_2km, justifies column dropping

X_train_ols = sm.add_constant(X_train.astype(float))
X_test_ols  = sm.add_constant(X_test.astype(float))

ols_model = sm.OLS(y_train, X_train_ols).fit()

# Print full statistical summary
print("\n" + "="*60)
print("OLS FULL SUMMARY")
print("="*60)
print(ols_model.summary())

# OLS predictions and metrics
y_pred_ols = ols_model.predict(X_test_ols)
ols_rmse = np.sqrt(mean_squared_error(y_test, y_pred_ols))
ols_r2   = r2_score(y_test, y_pred_ols)
print(f"\n[OLS] RMSE: ${ols_rmse:,.0f} | R²: {ols_r2:.4f}")

# 5.1 School effect interpretation
print("\n" + "="*60)
print("SCHOOL PROXIMITY EFFECT ON RESALE PRICE (OLS)")
print("Each coefficient = SGD premium per additional good school in that band")
print("="*60)
for col in SCHOOL_COLS:
    coef   = ols_model.params[col]
    pval   = ols_model.pvalues[col]
    ci_low = ols_model.conf_int().loc[col, 0]
    ci_hi  = ols_model.conf_int().loc[col, 1]
    sig    = "***" if pval < 0.001 else "**" if pval < 0.01 else "*" if pval < 0.05 else "(not sig)"
    print(f"  {col:<22}: ${coef:>10,.0f}  p={pval:.4f} {sig}  "
          f"95% CI: [${ci_low:,.0f}, ${ci_hi:,.0f}]")

# 5.2 VIF check on school variables (multicollinearity)
# Only compute VIF for school + key numeric variables (VIF on all dummies is unstable)
vif_cols = SCHOOL_COLS + ['floor_area_sqm', 'storey_mid', 'mrt_dist',
                           'hawker_dist', 'remaining_lease_2026', 'sold_year']
vif_subset = X_train[vif_cols].astype(float)
vif_df = pd.DataFrame({
    'Feature': vif_cols,
    'VIF': [variance_inflation_factor(vif_subset.values, i)
            for i in range(vif_subset.shape[1])]
}).sort_values('VIF', ascending=False)
print("\n--- VIF (key variables) ---")
print(vif_df.to_string(index=False))
print("Note: VIF > 10 signals problematic multicollinearity")

#Shows a correlation of exactly 1.0 between the two, meaning that one is completely redundant given the other

print(df[['lease_commence_date', 'remaining_lease_2026']].corr())

# Pre-OLS: Drop multicollinear columns identified via VIF diagnostics
# good_sch_gt_2km: VIF = 53,489 (near-perfect linear combination of other school variables)
# lease_commence_date: nearly identical to remaining_lease_2026 (correlation ≈ -1.0)
cols_to_drop_for_ols = ['good_sch_gt_2km', 'lease_commence_date']
X_train_fixed = X_train.drop(columns=cols_to_drop_for_ols)
X_test_fixed  = X_test.drop(columns=cols_to_drop_for_ols)

# Update SCHOOL_COLS to reflect dropped column
SCHOOL_COLS = ['good_sch_lt_1km', 'good_sch_1_2km']

# ============================================================
# SECTION 5B: OLS — HEDONIC PRICING MODEL (MAIN MODEL, after multicollinearity fix)
# ============================================================
# Coefficients on school variables = estimated price premium for proximity to a good primary school, holding all else constant.

X_train_ols = sm.add_constant(X_train_fixed.astype(float))
X_test_ols  = sm.add_constant(X_test_fixed.astype(float))

ols_model = sm.OLS(y_train, X_train_ols).fit()

# Print full statistical summary
print("\n" + "="*60)
print("OLS FULL SUMMARY")
print("="*60)
print(ols_model.summary())

# OLS predictions and metrics
y_pred_ols = ols_model.predict(X_test_ols)
ols_rmse = np.sqrt(mean_squared_error(y_test, y_pred_ols))
ols_r2   = r2_score(y_test, y_pred_ols)
print(f"\n[OLS] RMSE: ${ols_rmse:,.0f} | R²: {ols_r2:.4f}")

# 5.1 School effect interpretation
print("\n" + "="*60)
print("SCHOOL PROXIMITY EFFECT ON RESALE PRICE (OLS)")
print("Each coefficient = SGD premium per additional good school in that band")
print("="*60)
for col in SCHOOL_COLS:
    coef   = ols_model.params[col]
    pval   = ols_model.pvalues[col]
    ci_low = ols_model.conf_int().loc[col, 0]
    ci_hi  = ols_model.conf_int().loc[col, 1]
    sig    = "***" if pval < 0.001 else "**" if pval < 0.01 else "*" if pval < 0.05 else "(not sig)"
    print(f"  {col:<22}: ${coef:>10,.0f}  p={pval:.4f} {sig}  "
          f"95% CI: [${ci_low:,.0f}, ${ci_hi:,.0f}]")

# 5.2 VIF check on school variables (multicollinearity)
# Only compute VIF for school + key numeric variables (VIF on all dummies is unstable)
vif_cols = ['good_sch_lt_1km', 'good_sch_1_2km',
            'floor_area_sqm', 'storey_mid', 'mrt_dist',
            'hawker_dist', 'remaining_lease_2026', 'sold_year']
vif_subset = X_train_fixed[vif_cols].astype(float)
vif_df = pd.DataFrame({
    'Feature': vif_cols,
    'VIF': [variance_inflation_factor(vif_subset.values, i)
            for i in range(vif_subset.shape[1])]
}).sort_values('VIF', ascending=False)
print("\n--- VIF (key variables) ---")
print(vif_df.to_string(index=False))
print("Note: VIF > 10 signals problematic multicollinearity")

# ============================================================
# SECTION 6: RIDGE REGRESSION
# ============================================================

ridge_cv = RidgeCV(alphas=np.logspace(0, 6, 20), cv=3)  # faster run settings
ridge_cv.fit(X_train_fixed, y_train)

y_pred_ridge = ridge_cv.predict(X_test_fixed)
ridge_rmse = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
ridge_r2   = r2_score(y_test, y_pred_ridge)

print(f"\n[Ridge] Best alpha: {ridge_cv.alpha_:.4f} | "
      f"RMSE: ${ridge_rmse:,.0f} | R²: {ridge_r2:.4f}")

ridge_coefs = pd.Series(ridge_cv.coef_, index=X_train_fixed.columns)
print("  Ridge school coefficients:")
for col in SCHOOL_COLS:
    print(f"    {col}: ${ridge_coefs[col]:,.0f}")

# ============================================================
# SECTION 7: LASSO REGRESSION
# ============================================================
# Lasso can shrink some coefficients to exactly zero (feature selection).
# If school variables survive Lasso, it's a strong evidence of their importance.

lasso_cv = LassoCV(alphas=np.logspace(-3, 4, 20), cv=3, max_iter=10000, n_jobs=-1)  # faster run settings
lasso_cv.fit(X_train_fixed, y_train)

y_pred_lasso = lasso_cv.predict(X_test_fixed)
lasso_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lasso))
lasso_r2   = r2_score(y_test, y_pred_lasso)

print(f"\n[Lasso] Best alpha: {lasso_cv.alpha_:.4f} | "
      f"RMSE: ${lasso_rmse:,.0f} | R²: {lasso_r2:.4f}")

lasso_coefs = pd.Series(lasso_cv.coef_, index=X_train_fixed.columns)
n_zeroed = (lasso_coefs == 0).sum()
print(f"  Features zeroed out by Lasso: {n_zeroed} / {len(lasso_coefs)}")
print("  Lasso school coefficients:")
for col in SCHOOL_COLS:
    zeroed = " (zeroed out)" if lasso_coefs[col] == 0 else ""
    print(f"    {col}: ${lasso_coefs[col]:,.0f}{zeroed}")

# ============================================================
# SECTION 8: RANDOM FOREST
# ============================================================

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    max_samples=0.5  # subsampling for speed
)
rf_model.fit(X_train_fixed, y_train)

y_pred_rf = rf_model.predict(X_test_fixed)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
rf_r2   = r2_score(y_test, y_pred_rf)

print(f"\n[Random Forest] RMSE: ${rf_rmse:,.0f} | R²: {rf_r2:.4f}")

# Feature importance
rf_importance = pd.Series(rf_model.feature_importances_, index=X_train_fixed.columns)
print("\n  Top 15 features (Random Forest importance):")
print(rf_importance.nlargest(15).to_string())
print("\n  School feature importance (RF):")
for col in SCHOOL_COLS:
    print(f"    {col}: {rf_importance[col]:.4f}")

# ============================================================
# SECTION 9: XGBOOST
# ============================================================

from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=300, learning_rate=0.05, max_depth=6,
    subsample=0.8, colsample_bytree=0.8,
    random_state=42, n_jobs=-1, verbosity=0
)
xgb_model.fit(X_train_fixed, y_train,
              eval_set=[(X_test_fixed, y_test)],
              verbose=False)

y_pred_xgb = xgb_model.predict(X_test_fixed)
xgb_rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
xgb_r2   = r2_score(y_test, y_pred_xgb)

print(f"\n[XGBoost] RMSE: ${xgb_rmse:,.0f} | R²: {xgb_r2:.4f}")

# XGBoost feature importance
xgb_importance = pd.Series(xgb_model.feature_importances_, index=X_train_fixed.columns)
print("\n  Top 15 features (XGBoost importance):")
print(xgb_importance.nlargest(15).to_string())
print("\n  School feature importance (XGBoost):")
for col in SCHOOL_COLS:
    print(f"    {col}: {xgb_importance[col]:.4f}")

# ============================================================
# SECTION 10: MODEL COMPARISON TABLE
# ============================================================

results = pd.DataFrame({
    'Model':  ['Baseline (Mean)', 'OLS', 'Ridge', 'Lasso', 'Random Forest', 'XGBoost'],
    'RMSE':   [baseline_rmse, ols_rmse, ridge_rmse, lasso_rmse, rf_rmse, xgb_rmse],
    'R²':     [baseline_r2,   ols_r2,   ridge_r2,   lasso_r2,   rf_r2,   xgb_r2]
}).sort_values('RMSE').reset_index(drop=True)

results['RMSE_fmt'] = results['RMSE'].apply(lambda x: f"${x:,.0f}")
results['R²_fmt']   = results['R²'].apply(lambda x: f"{x:.4f}")

print("\n" + "="*60)
print("MODEL COMPARISON SUMMARY")
print("="*60)
print(results[['Model', 'RMSE_fmt', 'R²_fmt']].rename(
    columns={'RMSE_fmt': 'RMSE', 'R²_fmt': 'R²'}).to_string(index=False))

# ============================================================
# SECTION 11: VISUALISATIONS
# ============================================================

sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 130

# Plot 1: Model Comparison (RMSE & R²)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Model Comparison", fontsize=14, fontweight='bold')

r_rmse = results.sort_values('RMSE', ascending=False)
colors = ['#d9534f' if m == 'Baseline (Mean)' else '#5b9bd5' for m in r_rmse['Model']]

axes[0].barh(r_rmse['Model'], r_rmse['RMSE'], color=colors)
axes[0].set_xlabel('RMSE (SGD) — lower is better')
axes[0].set_title('Root Mean Squared Error')
for i, v in enumerate(r_rmse['RMSE']):
    axes[0].text(v * 0.01, i, f"${v:,.0f}", va='center', fontsize=8)

r_r2 = results.sort_values('R²', ascending=True)
colors2 = ['#d9534f' if m == 'Baseline (Mean)' else '#70ad47' for m in r_r2['Model']]
axes[1].barh(r_r2['Model'], r_r2['R²'], color=colors2)
axes[1].set_xlabel('R² — higher is better')
axes[1].set_title('R-Squared')
for i, v in enumerate(r_r2['R²']):
    axes[1].text(v * 0.01, i, f"{v:.4f}", va='center', fontsize=8)

plt.tight_layout()
plt.savefig('model_comparison.png', bbox_inches='tight')
plt.show()
print("Saved: model_comparison.png")

# Plot 2: School Effect (OLS coefficients with 95% CI)
school_labels = ['< 1km', '1–2km']
coefs  = [ols_model.params[c] for c in SCHOOL_COLS]
ci_low = [ols_model.conf_int().loc[c, 0] for c in SCHOOL_COLS]
ci_hi  = [ols_model.conf_int().loc[c, 1] for c in SCHOOL_COLS]
err_lo = [c - l for c, l in zip(coefs, ci_low)]
err_hi = [h - c for c, h in zip(coefs, ci_hi)]

fig, ax = plt.subplots(figsize=(8, 5))
bar_colors = ['#2ecc71' if c > 0 else '#e74c3c' for c in coefs]
bars = ax.barh(school_labels, coefs,
               xerr=[err_lo, err_hi],
               color=bar_colors, capsize=6, alpha=0.85,
               error_kw={'elinewidth': 1.5, 'ecolor': 'black'})
ax.axvline(0, color='black', linestyle='--', linewidth=1)
ax.set_xlabel('Effect on Resale Price (SGD)', fontsize=11)
ax.set_title('Effect of Good Primary School Proximity on HDB Resale Price\n'
             '(OLS Coefficients with 95% Confidence Intervals, per additional school)',
             fontsize=11, fontweight='bold')
for bar, coef in zip(bars, coefs):
    if coef >= 0:
        ax.text(coef + 500, bar.get_y() + bar.get_height()/2,
                f"${coef:,.0f}", va='center', ha='left',
                fontsize=10, fontweight='bold')
    else:
        ax.text(coef, bar.get_y() + bar.get_height() + 0.02,
                f"${coef:,.0f}", va='bottom', ha='center',
                fontsize=10, fontweight='bold')
ax.set_xlim(min(ci_low) * 1.3, max(ci_hi) * 1.3)
plt.tight_layout()
plt.savefig('school_effect_ols.png', bbox_inches='tight')
plt.show()
print("Saved: school_effect_ols.png")

# Plot 3: Actual vs Predicted (Random Forest - best model)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Actual vs Predicted — Random Forest", fontsize=13, fontweight='bold')

sample_idx = np.random.choice(len(y_test), size=min(5000, len(y_test)), replace=False)
axes[0].scatter(y_test.iloc[sample_idx] / 1e6, y_pred_rf[sample_idx] / 1e6,
                alpha=0.15, s=5, color='steelblue')
lims = [min(y_test.min(), y_pred_rf.min()) / 1e6,
        max(y_test.max(), y_pred_rf.max()) / 1e6]
axes[0].plot(lims, lims, 'r--', lw=1.5, label='Perfect prediction')
axes[0].set_xlabel('Actual Price (SGD M)')
axes[0].set_ylabel('Predicted Price (SGD M)')
axes[0].set_title('Scatter: Actual vs Predicted')
axes[0].legend()

residuals = y_test.values - y_pred_rf
axes[1].scatter(y_pred_rf[sample_idx] / 1e6, residuals[sample_idx] / 1e3,
                alpha=0.15, s=5, color='coral')
axes[1].axhline(0, color='black', linestyle='--', lw=1.5)
axes[1].set_xlabel('Predicted Price (SGD M)')
axes[1].set_ylabel('Residual (SGD thousands)')
axes[1].set_title('Residuals vs Predicted')

plt.tight_layout()
plt.savefig('actual_vs_predicted_rf.png', bbox_inches='tight')
plt.show()
print("Saved: actual_vs_predicted_rf.png")

# Plot 4: Feature Importance (Random Forest top 15)
top15 = rf_importance.nlargest(15).sort_values()
bar_cols = ['#e67e22' if c in SCHOOL_COLS else '#3498db' for c in top15.index]

fig, ax = plt.subplots(figsize=(9, 6))
ax.barh(top15.index, top15.values, color=bar_cols)
ax.set_xlabel('Feature Importance (Random Forest)')
ax.set_title('Top 15 Features — Random Forest\n(orange = school proximity features)',
             fontweight='bold')
plt.tight_layout()
plt.savefig('feature_importance_rf.png', bbox_inches='tight')
plt.show()
print("Saved: feature_importance_rf.png")

print("\n✅ All done. Key outputs:")
print("   - model_comparison.png")
print("   - school_effect_ols.png  ← main result for research question")
print("   - actual_vs_predicted_rf.png")
print("   - feature_importance_rf.png")